### ISSUE TITLE
ノイズの追加

### ISSUE THREAD

**Issue by l1sum** [l1sum/sound_system#1]
雑音による誤認識を防ぐために、ノイズの追加をお願いします.

**Comment by yamatomatsuda** [comment]
追加しました。各自pathを自分のものに書き換えて、認識度合いの確認をしてください

**Comment by l1sum** [comment]
ありがとう！
Pathに関してだけど、ワークスペース直下にpkgが存在することを想定してる。
こうすることで、プログラム内のパス指定を絶対パスではなく、pkg名からの相対パスで指定できるよ！
今後は相対パスで書くようにしてね！

**Comment by yamatomatsuda** [comment]
相対でかけないのは、ros2 run で実行しているファイルがinstallにあるからなんだけど、どう考えてる？

**Comment by l1sum** [comment]
>>>相対でかけないのは、ros2 run で実行しているファイルがinstallにあるからなんだけど、どう考えてる？
globを使ってros2 runの実行時にpathをどこ基準で生成しているのかを確認したら、
現在自分がいるディレクトリを基準にpathを生成してるみたい.
なので、現状僕のmacbookairでもjetson nanoでも相対パスで動作するよ！

ただ、僕の環境はワークスペース直下にpkgがあるからsound_system/...とできるけど、直下にsrcがあるならsrc/sound_system/...に書き換えたほうがいいね！
ここは正直各個人の環境に依存しちゃうから統一すれば修正可能.

提案としては
1. 絶対パスを生成する関数の作成
2. ディレクトリ構造の統一化による相対パスの利用
