### ISSUE TITLE
sound_systemにsound_detectionを含めるか

### ISSUE THREAD

**Issue by yamatomatsuda** [l1sum/sound_system#6]
sound_detectionは肥大化する可能性があるので、非推奨だとおもわれる

**Comment by l1sum** [comment]
必要な機能は統合するべきだと思う.
それに、増えても200行程度のことだし,問題ないのでは？

**Comment by yamatomatsuda** [comment]
そうすると部分、部分の構造が捉えづらいのでリファクタリングしづらい
